### PR TITLE
4 - Implement paragraphs within the toggle

### PR DESCRIPTION
**Pull request by juliansg022**
Developing #4

### CODE REVIEW

**Comment by juliansg022** [comment]
Closes #4

Hi @juanhurtado10, I've implemented a most complete toggle version


## Context
In a toggle you should be able to insert paragraphs from your tools (first icon) and also delete your paragraphs (second icon - the last available paragraph in the toggle is always deleted). Additionally, when clicking on the main icon of the toggle it is possible to hide its paragraphs (closed status) and show them again (open status).


## Description
The following animated image (gif) can summarize the toggle functionality

Animation

**Comment by juanhurtado10** [comment]
@juliansg022 looks awesome  👏 . 

It would be great if we can avoid controls for adding/removing new items into the toggle element. My thought is to keep it simple and just use ENTER and DELETE for these actions. Is that possible?

**Comment by juliansg022** [comment]
@juanhurtado10  Yes, I think it's possible. I had contemplated making those shortcut adjustments in #5.

**Comment by juanhurtado10** [comment]
> @juanhurtado10 Yes, I think it's possible. I had contemplated making those shortcut adjustments in #5.

@juliansg022 OK, cool!! Let's move forward then 🚀

**Review by juanhurtado10 — APPROVED** [review]

**Pull request merged**
